version: '3'

services:
  iobroker:
    restart: always
    image: iobroker/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - ..:/opt/iobroker/node_modules/iobroker.procon-ip
